### ISSUE TITLE
Single file import appears broken

### ISSUE THREAD

**Issue by thetwoj** [THADEUSH123/design-transformer#1]
```
jjgraham@jjgraham-mbp:~/Desktop/Thad/deployment-san-jose $ ls
From TechM - Area 2 planned site locations 01 10 17- submittal order.csv cn-links.gv
README.md                                                                cn-sites.csv
area1.gv                                                                 non-cmo-locations.csv
area2.gv                                                                 streetlight-cmo-export.csv
area3.gv                                                                 suspect-poles.csv
```
```
jjgraham@jjgraham-mbp:~/Desktop/Thad/deployment-san-jose $ data_transformer 

============MAIN MENU=================
Select an action to perform:
1 => Load data.
2 => Export data.
3 => Exit
Enter choice[1]: 

============IMPORT MENU=================
Load multiple data sets in the following ways:
1 => Import multiple files from a folder
2 => Import one specific file
3 => Do not load additional files
Enter menu choice[1]: 2
Enter file name[None]: area1.gv
Traceback (most recent call last):
  File "/usr/local/bin/data_transformer", line 9, in <module>
    load_entry_point('data-transformer==0.1', 'console_scripts', 'data_transformer')()
  File "build/bdist.macosx-10.12-intel/egg/data_transformer/__main__.py", line 125, in main
  File "build/bdist.macosx-10.12-intel/egg/data_transformer/__main__.py", line 81, in import_menu
  File "build/bdist.macosx-10.12-intel/egg/data_transformer/datastore.py", line 48, in __getattr__
AttributeError
```
```
jjgraham@jjgraham-mbp:~/Desktop/Thad/deployment-san-jose $ data_transformer 

============MAIN MENU=================
Select an action to perform:
1 => Load data.
2 => Export data.
3 => Exit
Enter choice[1]: 

============IMPORT MENU=================
Load multiple data sets in the following ways:
1 => Import multiple files from a folder
2 => Import one specific file
3 => Do not load additional files
Enter menu choice[1]: 2
Enter file name[None]: area2.gv
Traceback (most recent call last):
  File "/usr/local/bin/data_transformer", line 9, in <module>
    load_entry_point('data-transformer==0.1', 'console_scripts', 'data_transformer')()
  File "build/bdist.macosx-10.12-intel/egg/data_transformer/__main__.py", line 125, in main
  File "build/bdist.macosx-10.12-intel/egg/data_transformer/__main__.py", line 81, in import_menu
  File "build/bdist.macosx-10.12-intel/egg/data_transformer/datastore.py", line 48, in __getattr__
AttributeError
```

**Comment by THADEUSH123** [comment]
Thanks @thetwoj 
![test in prod](https://cloud.githubusercontent.com/assets/9945102/22721610/a683f0da-ed66-11e6-94c1-5f5fee33a374.jpg)
